name: Run tox

on:
  push:

jobs:
  main:
    name: Run it
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install -r requirements.txt
          python -m pip install tox-gh-actions==2.2.0

      - name: "Run tox for ${{ matrix.python-version }}"
        run: |
          python -m tox -q
